# - name: Setup Cluster Component
#   hosts: all
#   become: true
#   gather_facts: true
#   roles:
#   - role: backup_k8s

- name: upgrade the kubelet and kubectl
  hosts: all
  become: true
  gather_facts: true
  serial: 1
  tasks:
  - include_role:
      name: debian_upgrade
