---
- name: Backup Kubernetes Components
  hosts: all
  gather_facts: true
  become: true
  roles:
  - role: backup_k8s

- name: Upgrade the whole kubernetes cluster server by server
  hosts: all
  gather_facts: true
  become: true
  serial: 1
  tasks:
  - name: Include OS-specific upgrade role
    include_role:
      name: "{{ 'rhel_upgrade' if ansible_os_family == 'RedHat' else 'debian_upgrade' }}"
    vars:
      kube_config: "/home/ansible/.kube/config"
