- name: Determine upgrade version
  ansible.builtin.include_tasks: kubeadm-upgrade-debian.yml

- name: Determine upgrade version
  ansible.builtin.include_tasks: kubeadm_upgrade_plan.yml

- name: Determine upgrade version
  ansible.builtin.include_tasks: upgrade_kubelet_kubectl_debian.yml
